title: Matteas Eden # your name (or website title) here
logo: "/images/profile-pic.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I'm a final year Computer Systems Engineering student at the University of Auckland, New Zealand.
  <br><br>
  This is a simple page demonstrating some of the projects I've worked on over the past few years.
  <br><br>
  <a href="https://www.linkedin.com/in/matteaseden/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
